# Generated by Django 5.2.13 on 2026-04-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='Editora',
            new_name='editora',
        ),
    ]
